version: 0.2

phases:
  pre_build:
    commands:
      # Authenticate Docker to ECR
      - echo Obteniendo Credenciales
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 471112942110.dkr.ecr.us-west-1.amazonaws.com
      
      # Set image tag variables for both images
      - IMAGE1_REPOSITORY_URI = 471112942110.dkr.ecr.us-west-1.amazonaws.com/service-a
      - IMAGE1_TAG=latest
      - IMAGE2_REPOSITORY_URI = 471112942110.dkr.ecr.us-west-1.amazonaws.com/service-b
      - IMAGE2_TAG=latest
  build:
    commands:
      - echo Building the first Docker image...
      - docker build -t $IMAGE1_REPOSITORY_URI:$IMAGE1_TAG -f service-a/Dockerfile --no-cache .
      - echo Building the second Docker image...
      - docker build -t $IMAGE2_REPOSITORY_URI:$IMAGE2_TAG -f service-b/Dockerfile --no-cache .
  post_build:
    commands:
      - echo Pushing the first Docker image to Amazon ECR...
      - docker push $IMAGE1_REPOSITORY_URI:$IMAGE1_TAG
      - echo Pushing the second Docker image to Amazon ECR...
      - docker push $IMAGE2_REPOSITORY_URI:$IMAGE2_TAG
artifacts:
  files:
    - Dockerrun.aws.json
