version: 0.2

phases:
  install:
    commands:
      # Authenticate Docker to ECR
      - echo Obteniendo Credenciales
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 471112942110.dkr.ecr.us-west-1.amazonaws.com
  pre_build:
    commands:
      - echo Building Docker images
      - docker build --no-cache -t service-a-image ./service-a
  build:
    commands:
      - echo Tagging Docker images
      - docker tag service-a-image:latest 471112942110.dkr.ecr.us-west-1.amazonaws.com/service-a:latest
  post_build:
    commands:
      - echo Pushing the first Docker image to Amazon ECR...
      - docker push 471112942110.dkr.ecr.us-west-1.amazonaws.com/service-a:latest
artifacts:
  files:
    - cd ..
    - docker-compose.yml
    #- Dockerrun.aws.json